#cloud-config
# The above header must generally appear on the first line of a cloud config
# file, but all other lines that begin with a # are optional comments.


packages:
  - apt-transport-https
  - jq
  - curl
  - htop
  - unattended-upgrades
  - update-notifier-common

runcmd:
  # One-command install, from https://tailscale.com/download/
  - ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh']
  # Set sysctl settings for IP forwarding (useful when configuring an exit node)
  - ['sh', '-c', "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf" ]
  # start tailscale
  - ['tailscale', 'up', '--auth-key=${auth_key}', '--ssh', '--advertise-exit-node']

  # Use Oracle metadata endpoint to set reboot hour from availability domain and minute from fault domain
  - |
    for i in $(seq 1 10); do
      METADATA_JSON=$(curl -s -H "Authorization: Bearer Oracle" "http://169.254.169.254/opc/v2/instance/")
      AD=$(echo "$METADATA_JSON" | jq --raw-output '.availabilityDomain')
      FD=$(echo "$METADATA_JSON" | jq --raw-output '.faultDomain')
      if [ -n "$AD" ] && [ -n "$FD" ] && [ "$AD" != "null" ] && [ "$FD" != "null" ]; then
        break
      fi
      sleep 5
    done

    REBOOT_HOUR="$(echo $AD | sed -E 's/.*-([0-9]+)/0\1/')"
    REBOOT_MINUTE="$(echo $FD | sed -E 's/.*-([0-9]+)/\10/')"
    REBOOT_TIME="$REBOOT_HOUR:$REBOOT_MINUTE"

    # Enable automatic updates to reboot
    sed -i 's|^//Unattended-Upgrade::Automatic-Reboot "false";|Unattended-Upgrade::Automatic-Reboot "true";|' /etc/apt/apt.conf.d/50unattended-upgrades

    # Update unattended-upgrades config to set reboot time
    sed -i "s|^//Unattended-Upgrade::Automatic-RebootTime.*$|Unattended-Upgrade::Automatic-RebootTime \"$REBOOT_TIME\";|" /etc/apt/apt.conf.d/50unattended-upgrades


  # Enable and start unattended-upgrades
  - ['systemctl', 'enable', '--now', 'unattended-upgrades']
