---
image:
    repository: linuxserver/radarr
    # Overrides the image tag whose default is the chart appVersion.
    pullPolicy: Always

volumes:
    config:
        source: "/home/docker/radarr/config"
        dest: "/config"
    downloads:
        source: "/red/downloads"
        dest: "/red/downloads"
    blackhole:
        source: "/red/blackhole"
        dest: "/red/blackhole"
    movies:
        source: "/red/Movies"
        dest: "/movies"


environment:
    - name: PUID
      value: "113"
    - name: GUID
      value: "117"
    - name: TZ
      value: Africa/Johannaesburg

ports:
    http:
        target: 7878
        protocol: TCP

ingress:
  annotations:
#     kubernetes.io/ingress.class: public
#     kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: radarr.lan
      path: /
      service:
        name: http
    - host: radarr.arendse.nom.za
      tls: true
      path: /
      service:
        name: http
    - host: 6f3806410f7b.sn.mynetname.net
      tls: true
      path: /radarr
      service:
        name: http

