---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: echo
  labels:
    name: echo
  # annotations:
    # kubernetes.io/ingress.class: "public"
spec:
  ingressClassName: public
  tls:
    - hosts:
      - arendse.ddns.net
      secretName: echo
  rules:
  - host: arendse.ddns.net
    http:
      paths:
      - pathType: Prefix
        path: /echo
        backend:
          service:
            name: echo
            port:
              name: http
