{{ $root := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}

  {{- with .Values.ports }}
  ports:
    {{- range $key, $val := . }}
    - name: {{ $key }}
      targetPort: {{ $key }}
      port: {{ $val.target }}
      protocol: {{ $val.protocol }}
      {{- if eq $root.Values.service.type "NodePort" }}
      nodePort: {{ $val.nodePort }}
      {{- end }}
    {{ end -}}
  {{- end }}
