# Default values for server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

environment:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: Africa/Johannaesburg

# volumes: {}
    # name:
        # source: ""
        # dest: ""
ports:
    http:
        source: 80
        target: 80
        protocol: TCP

ingress:
  annotations: {}
#     kubernetes.io/ingress.class: public
#     kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart.lan
      paths:
        - path: /
          service:
            name: http
    - host: chart-example.local
      paths:
        - path: /
          service:
            name: http
      tls:
        secretName: chart-example-tls
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
