image:
    repository: lscr.io/linuxserver/prowlarr
    # Overrides the image tag whose default is the chart appVersion.
    tag: nightly
    pullPolicy: Always

volumes:
    config:
        source: "/home/docker/prowlarr/config"
        dest: "/config"

environment:
    - name: PUID
      value: "113"
    - name: GUID
      value: "117"
    - name: TZ
      value: Africa/Johannaesburg

ports:
    http:
        target: 9696
        protocol: TCP

ingress:
  annotations:
#     kubernetes.io/ingress.class: public
#     kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: prowlarr.lan
      path: /
      service:
        name: http
    - host: prowlarr.arendse.nom.za
      tls: true
      path: /
      service:
        name: http
    - host: 6f3806410f7b.sn.mynetname.net
      tls: true
      path: /prowlarr
      service:
        name: http
