apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 400
      my-asn: 300
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.10.0/24
    - name: pihole
      protocol: bgp
      addresses:
      - 192.168.100.1/32
