---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
    config: |
        peers:
            -   peer-address: 192.168.1.1
                peer-asn: 400
                my-asn: 300
        address-pools:
            -   name: default
                protocol: layer2
                addresses:
                    -   192.168.1.250-192.168.1.254
            -   name: pihole
                protocol: layer2
                addresses:
                    -   192.168.1.200/31
            -   name: trintiy
                protocol: layer2
                addresses:
                    -   192.168.1.234/31
