apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 400
      my-asn: 300
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.1.200-192.168.1.254
      # 192.168.1.225 - 192.168.1.254
    - name: pihole
      protocol: bgp
      addresses:
      - 192.168.1.200/32
    - name: trintiy
      protocol: bgp

