# $ docker run --pull=always --restart=unless-stopped -d -p 5006:5006 -v YOUR/PATH/TO/DATA:/data --name my_actual_budget actualbudget/actual-server:latest
---
image:
  repository: actualbudget/actual-server
  tag: edge-alpine

volumes:
  data:
    source: "/mnt/data/actual/data"
    dest: "/data"

environment:
  - name: TZ
    value: Africa/Johannaesburg

  - name: ACTUAL_PORT
    value: "5006"

ports:
  http:
    target: 5006
    protocol: TCP

ingress:
  hosts:
    - host: arendse.nom.za
      tls: true
      path: /actual
      service:
        name: http

    - host: actual.arendse.nom.za
      tls: true
      path: /
      service:
        name: http

    - host: arendse.ddns.net
      tls: true
      path: /actual
      service:
        name: http
