image:
    repository: plexinc/pms-docker
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    pullPolicy: Always

volumes:
    config:
        source: "/mnt/data/plex/config"
        dest: "/config"
    transcode:
        source: "/mnt/data/plex/transcode"
        dest: "/transcode"
    data:
        source: "/red"
        dest: "/red"

environment:
    - name: ADVERTISE_IP 
      value: http://192.168.0.50:32400
    - name: HOSTNAME
      value: "arendse.ddns.net"
    - name: PLEX_UID
      value: "114"
    - name: PLEX_GID
      value: "118"
    - name: TZ
      value: Africa/Johannaesburg

secrets:
  environment:
    - plex-secret

service:
  type: NodePort

ports:
# https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
  # (access to the Plex Media Server) [required]
  plexmediaserver: 
    target: 32400
    nodePort: 32400
    protocol: TCP
  # (older Bonjour/Avahi network discovery)
  # bonjour:
  #   target: 5353
  #   protocol: UDP
  # # (controlling Plex for Roku via Plex Companion)
  # plexcompanion:
  #   target: 8324
  #   nodePort: 30324
  #   protocol: TCP
  # # (access to the Plex DLNA Server)
  # dlna-tcp:
  #   target: 32469
  #   nodePort: 30469
  #   protocol: TCP
  # # (access to the Plex DLNA Server)
  # dlna-udp:
  #   target: 1900
  #   nodePort: 30190
  #   protocol: UDP
  # # (current GDM network discovery)
  # gdm-10:
  #   target: 32410
  #   nodePort: 30410
  #   protocol: UDP
  # gdm-12:
  #   target: 32412
  #   nodePort: 30412
  #   protocol: UDP
  # gdm-13:
  #   target: 32413
  #   nodePort: 30413
  #   protocol: UDP
  # gdm-14:
  #   target: 32414
  #   nodePort: 30414
  #   protocol: UDP

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: arendse.nom.za
      tls: true
      path: /plex
      service:
        name: plexmediaserver
    - host: plex.arendse.nom.za
      tls: true
      path: /
      service:
        name: plexmediaserver
    - host: arendse.ddns.net
      tls: true
      path: /plex
      service:
        name: plexmediaserver

