image:
    repository: plexinc/pms-docker
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    pullPolicy: Always

volumes:
    config:
        source: "/home/plex/config"
        dest: "/config"
    transcode:
        source: "/home/plex/transcode"
        dest: "/transcode"
    data:
        source: "/red"
        dest: "/red"

environment:
    - name: ADVERTISE_IP 
      value: 192.168.0.50
    - name: PLEX_UID
      value: "114"
    - name: PLEX_GID
      value: "118"
    - name: TZ
      value: Africa/Johannaesburg

ports:
# https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
  # (access to the Plex Media Server) [required]
  plexmediaserver: 
    target: 32400
    protocol: TCP
  # (older Bonjour/Avahi network discovery)
  bonjour:
    target: 5353
    protocol: UDP
  # (controlling Plex for Roku via Plex Companion)
  plexcompanion:
    target: 8324
    protocol: TCP
  # (access to the Plex DLNA Server)
  dlna-tcp:
    target: 32469
    protocol: TCP
  # (access to the Plex DLNA Server)
  dlna-udp:
    target: 1900
    protocol: UDP
  # (current GDM network discovery)
  gdm-10:
    target: 32410
    protocol: UDP
  gdm-12:
    target: 32412
    protocol: UDP
  gdm-13:
    target: 32413
    protocol: UDP
  gdm-14:
    target: 32414
    protocol: UDP
