---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  hosts:
    - role: "controller+worker"
      noTaints: true
      environment:
        ETCD_UNSUPPORTED_ARCH: "arm"
      openSSH:
        address: oci-alpha
        user: ubuntu
        keyPath: ~/.ssh/id_ed25519

    - role: "controller+worker"
      noTaints: true
      environment:
        ETCD_UNSUPPORTED_ARCH: "arm"
      openSSH:
        address: oci-bravo
        user: ubuntu
        keyPath: ~/.ssh/id_ed25519

  k0s:
    version: null
    versionChannel: stable
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          externalAddress: "kubernetes.arendse.nom.za"
          sans:
            - "kubernetes.arendse.nom.za"
            - "79.72.69.181"
            - "10.100.1.247"
            - "10.200.0.1"
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.200.0.0/16
          provider: calico
          calico:
            envVars:
              FELIX_IPTABLESMASK: "0xff00ff00"
              IP_AUTODETECTION_METHOD: "interface=enp0s6"
              IP6_AUTODETECTION_METHOD: "interface=enp0s6"
            # mtu: 1230

        telemetry:
          enabled: false
        
        extensions:
          helm:
            repositories:
            # https://github.com/stevehipwell/helm-charts/tree/main/charts/vertical-pod-autoscaler
            - name: vertical-pod-autoscaler
              url: https://stevehipwell.github.io/helm-charts/
            # https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            charts:
            - name: vertical-pod-autoscaler
              chartname: vertical-pod-autoscaler/vertical-pod-autoscaler
              version: "1.9.1"
              namespace: kube-system
              values: |
                enabled: true
                mode: "off"
            - name: ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              version: "4.12.3"
              namespace: ingress-nginx
              values: |
                controller:
                  progressDeadlineSeconds: 300
                  ingressClassResource:
                    name: public
                    default: true
                  service:
                    type: NodePort
                    nodePorts:
                      http: 32080
                      https: 32443
                  metrics:
                    enabled: true
                  podAnnotations:
                    prometheus.io/scrape: "true"
                    prometheus.io/port: "10254"
