name: Build and Upload Talos Image to Oracle Cloud

on:
  workflow_dispatch:

jobs:
  build-upload-talos-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TALOS_VERSION: "v1.11.2"

      OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
      OCI_BUCKET_NAME: ${{ secrets.OCI_BUCKET_NAME }}
      OCI_NAMESPACE: ${{ secrets.OCI_NAMESPACE }}

      OCI_CLI_USER: ${{ secrets.OCI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY}}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test OCI CLI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: test-oci-cli
        with:
          command: os ns get
          silent: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-utils \
            unzip

      - name: Download Talos ISO
        run: |
          curl -fsSL https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/${TALOS_VERSION}/oracle-amd64.raw.xz -o talos.raw.xz
          cat > image_metadata.json <<'EOF'
          {
              "version": 2,
              "externalLaunchOptions": {
                  "firmware": "UEFI_64",
                  "networkType": "PARAVIRTUALIZED",
                  "bootVolumeType": "PARAVIRTUALIZED",
                  "remoteDataVolumeType": "PARAVIRTUALIZED",
                  "localDataVolumeType": "PARAVIRTUALIZED",
                  "launchOptionsSource": "PARAVIRTUALIZED",
                  "pvAttachmentVersion": 2,
                  "pvEncryptionInTransitEnabled": true,
                  "consistentVolumeNamingEnabled": true
              },
              "imageCapabilityData": null,
              "imageCapsFormatVersion": null,
              "operatingSystem": "Talos",
              "operatingSystemVersion": "${TALOS_VERSION}",
              "additionalMetadata": {
                  "shapeCompatibilities": [
                      {
                          "internalShapeName": "VM.Standard.A1.Flex",
                          "ocpuConstraints": null,
                          "memoryConstraints": null
                      }
                  ]
              }
          }
          EOF

      - name: Extract the archive
        run: |
          xz --decompress talos.raw.xz

      - name: Convert to QCOW2
        run: |
          qemu-img convert -f raw -O qcow2 talos.raw talos.qcow2
      
      - name: Create an archive with metadata
        run: |
          tar zcf talos.oci talos.qcow2 image_metadata.json

      - name: Upload QCOW2 to Object Storage
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: >-
            os object put 
              --bucket-name $OCI_BUCKET_NAME 
              --name talos.oci 
              --file talos.oci 
              --namespace $OCI_NAMESPACE

      - name: Import Custom Image to OCI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: >-
            compute image import from-object 
              --compartment-id $OCI_COMPARTMENT_ID 
              --display-name "Talos Linux ${TALOS_VERSION} ARM64" 
              --os "Linux" 
              --launch-mode "NATIVE" 
              --bucket-name $OCI_BUCKET_NAME 
              --name talos.oci 
              --namespace $OCI_NAMESPACE


